CREATE TABLE Subjects(
	SubjectID INT IDENTITY(1, 1) PRIMARY KEY,
	SubjectName VARCHAR(50) NOT NULL
);

CREATE TABLE Majors(
	MajorID INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE Students(
	StudentID INT IDENTITY(1, 1) PRIMARY KEY,
	StudentNumber VARCHAR(50) NOT NULL,
	StudentName VARCHAR(50) NOT NULL,
	MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
);

CREATE TABLE Payments(
	PaymentID INT IDENTITY(1, 1) PRIMARY KEY,
	PaymentDate DATE NOT NULL,
	PaymentAmount DECIMAL(18,2) NOT NULL,
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
);

CREATE TABLE Agenda(
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
	SubjectID  INT FOREIGN KEY REFERENCES Subjects(SubjectID),
	PRIMARY KEY(StudentID, SubjectID)
);